# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Ghidra Nes Rom extension build

env:
  ghidra-url: https://ghidra-sre.org/ghidra_9.2.1_PUBLIC_20201215.zip
  ghidra-zip-filename: ghidra_9.2.1_PUBLIC.zip
  ghidra-directory: ghidra_9.2.1_PUBLIC

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download Ghidra release
      uses: carlosperate/download-file-action@v1.0.3
      id: download-ghidra
      with:
        file-url: ${{ env.ghidra-url }}
        file-name: ${{ env.ghidra-zip-filename }}

    - name: Unzip Ghidra
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq ${{ steps.download-ghidra.outputs.file-path }} -d .
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.2'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build extension
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: '6.8.2'
#         build-root-directory: ${{ github.workspace }}/build
        arguments: '-Pghidra.dir=${{ github.workspace }}/${{ env.ghidra-directory }} assemble'
    - name: list what we have
      run: find .
    - name: Upload built extension
      uses: actions/upload-artifact@v2
      with:
        name: extension
        path: build/dist/*.zip

  release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    needs: build

    steps:
    - name: Download built extension
      uses: actions/download-artifact@v2
      with:
        name: extension
    - name: Upload extension to release
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: '*.zip'
